#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp specter /tmp/release
VERSION=$(cat resources/SPECTER_CLI_VERSION)

cd /tmp/release

## release binary as zip archive

zip "specter-cli-$VERSION-$SPECTER_PLATFORM-amd64.zip" specter

## cleanup

rm specter
