#!/usr/bin/env bash

set -euo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

export PATH="$GRAALVM_HOME/bin:$PATH"
export JAVA_HOME="$GRAALVM_HOME"

mkdir -p classes
rm -rf classes/*

clojure -M -e "(compile 'specter-sci)"

"$GRAALVM_HOME/bin/gu" install native-image

"$GRAALVM_HOME/bin/native-image" \
    -cp classes:"$(clojure -Spath)" \
    --initialize-at-build-time \
    --no-server --no-fallback \
    -H:+ReportExceptionStackTraces \
    "-H:ReflectionConfigurationFiles=reflection.json" \
    "-H:Name=specter" \
    specter_sci
